descriptor-schema-version: "2.2"
info:
  name: bind9-acme
  version: "1.40"
app:
  cpuarch: x86_64
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    cpu: 500
    disk: 120
    memory: 256
    network:
    - interface-name: eth0
      ports: 
        udp: ["53"]
    profile: custom
  startup:
    rootfs: rootfs.tar
    target: 
      - /init.sh
  type: docker
